import jsPDF from 'jspdf';

export const generateReportPDF = (data: any) => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();

    // Helper for centering text
    const centerText = (text: string, y: number, size: number = 12, style: string = 'normal') => {
        doc.setFontSize(size);
        doc.setFont('helvetica', style);
        const textWidth = doc.getStringUnitWidth(text) * size / doc.internal.scaleFactor;
        const x = (pageWidth - textWidth) / 2;
        doc.text(text, x, y);
    };

    // --- HEADER ---
    doc.setFillColor(30, 58, 138); // Govt Navy Blue
    doc.rect(0, 0, pageWidth, 40, 'F');

    doc.setTextColor(255, 255, 255);
    centerText("GOVERNMENT OF INDIA", 15, 10, 'bold');
    centerText("MINISTRY OF RAILWAYS", 22, 14, 'bold');
    centerText("RAILWAY PROTECTION FORCE - AUTOMATED SURVEILLANCE REPORT", 32, 10, 'normal');

    // --- SESSION INFO ---
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text(`SESSION ID: ${data.session_id}`, 20, 55);
    doc.text(`DATE: ${new Date(data.timestamp).toLocaleString()}`, 20, 62);
    doc.text(`GENERATED BY: AI SURVEILLANCE SYSTEM (R-TAMPER-01)`, 20, 69);

    // --- VERDICT BOX ---
    const riskLevel = data.overall_assessment?.risk_level?.toUpperCase() || 'UNKNOWN';
    let riskColor = [100, 116, 139]; // Slate equivalent
    if (riskLevel === 'CRITICAL') riskColor = [220, 38, 38]; // Red
    else if (riskLevel === 'HIGH') riskColor = [234, 88, 12]; // Orange
    else if (riskLevel === 'LOW') riskColor = [22, 163, 74]; // Green

    doc.setDrawColor(riskColor[0], riskColor[1], riskColor[2]);
    doc.setFillColor(riskColor[0], riskColor[1], riskColor[2]);
    doc.rect(140, 50, 50, 20, 'FD');

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text(riskLevel, 148, 63); // Centered visually in box

    // --- SUMMARY SECTION ---
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text("EXECUTIVE SUMMARY", 20, 90);
    doc.setLineWidth(0.5);
    doc.line(20, 92, 190, 92);

    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    const summaryText = data.structured_output?.analysis_summary || "No summary available for this session.";
    const splitSummary = doc.splitTextToSize(summaryText, 170);
    doc.text(splitSummary, 20, 100);

    let currentY = 100 + (splitSummary.length * 7) + 10;

    // --- FINDINGS SECTION ---
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text("DETAILED FINDINGS", 20, currentY);
    doc.line(20, currentY + 2, 190, currentY + 2);
    currentY += 10;

    const findings = [
        `Tampering Detected: ${data.tampering_analysis?.tampering_assessment?.is_tampering_detected ? 'YES' : 'NO'}`,
        `Confidence Score: ${Math.round((data.overall_assessment?.confidence || 0) * 100)}%`,
        `Visual Anomalies: ${data.expert_results?.visual?.detections?.length || 0} detected`,
        `Structural Integrity: ${data.expert_results?.structural?.status || 'Active'}`,
    ];

    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    findings.forEach(finding => {
        doc.text(`• ${finding}`, 25, currentY);
        currentY += 7;
    });

    // --- ACTION RECOMMENDATIONS ---
    currentY += 5;
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text("ACTION RECOMMENDATIONS", 20, currentY);
    doc.line(20, currentY + 2, 190, currentY + 2);
    currentY += 10;

    const actions = data.action_report?.immediate_actions || ["No immediate actions required."];
    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');

    if (Array.isArray(actions)) {
        actions.forEach((action: string) => {
            const splitAction = doc.splitTextToSize(`• ${action}`, 170);
            doc.text(splitAction, 25, currentY);
            currentY += (splitAction.length * 7);
        });
    }

    // --- FOOTER ---
    const pageHeight = doc.internal.pageSize.getHeight();
    doc.setFontSize(8);
    doc.setTextColor(100, 100, 100);
    doc.text("This is a computer-generated report and does not require a physical signature.", 20, pageHeight - 20);
    doc.text(`Report Generated: ${new Date().toLocaleString()}`, 20, pageHeight - 15);
    doc.text("CONFIDENTIAL - FOR OFFICIAL USE ONLY", centerText("CONFIDENTIAL - FOR OFFICIAL USE ONLY", pageHeight - 10, 8) as any || 20, pageHeight - 10); // Center calc is manual here or just left align

    // Save
    doc.save(`RPF_Report_${data.session_id}.pdf`);
};
